_BASE_: "Base-RCNN-ShuffleNet-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_shufflenetv2_x1_0_flgc_fpn_backbone"
  WEIGHTS: "https://www.dropbox.com/s/raaqxkm993h2kxb/shufflenetv2_x1.0-72ccf27e.pth?dl=1"
  MASK_ON: False
  FPN:
    OUT_CHANNELS: 128
DATASETS:
  TRAIN: ("sku110_train",)
  TEST: ("sku110_test",)
OUTPUT_DIR: "checkpoints/FRCN-ShuffleNetV2-FLGC-FPNLite-1x"