_BASE_: "Base-RCNN-ShuffleNet-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_shufflenetv2_x0_5_fpn_backbone"
  WEIGHTS: "https://www.dropbox.com/s/1djcbgdf68571sg/shufflenetv2_x0.5-ce14aafc.pth?dl=1"
  MASK_ON: False
  FPN:
    OUT_CHANNELS: 128
DATASETS:
  TRAIN: ("sku110_train",)
  TEST: ("sku110_test",)
OUTPUT_DIR: "checkpoints/FRCN-ShuffleNetV2-FPNLite-1x"