_BASE_: "Base-RCNN-EfficientNet-FPN.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/f5v1umahqfv3e3u/efficientnet-b0-b18e8357.pth?dl=1"
  MASK_ON: False
  EFFICIENTNET:
    NAME: "efficientnet-b0" # efficientnet-b1, efficientnet-2,  ..., efficientnet-b7
  RESNETS:
    DEPTH: 50
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 12
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  LR_SCHEDULER_NAME: "WarmupCosineLR"
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "checkpoints/FRCN-EfficientNet-B0-FPN-1x"